import type {
  CMSCategory,
  CMSFeaturedConfig,
  CMSHeroBanner,
  CMSOrder,
  CMSProduct,
  CMSSettings,
} from "@/lib/cms/types"

const now = () => new Date().toISOString()

export const seedCategories: CMSCategory[] = [
  {
    id: "cat-internet",
    name: "Internet Only",
    slug: "internet-only",
    planType: "internet",
    description: "5G & fiber internet packages",
  },
  {
    id: "cat-bundle",
    name: "Internet + TV + Landline",
    slug: "home-bundles",
    planType: "bundle",
    description: "Ultra bundles with TV & voice",
  },
]

export const seedProducts: CMSProduct[] = [
  {
    id: "prod-home-starter-ultra",
    name: "DU Home Starter",
    description: "250 Mbps fiber · 24-month commitment",
    price: 292,
    originalPrice: 389,
    pricePeriod: "/month + 5% VAT",
    features: [
      "25% discount for specific buildings & areas · discounted lifetime AED 292 + 5% VAT = AED 306.60",
      "Speed: 250 Mbps · TV add-on: English Lite + Disney+",
      "Devices: 1 TV Box + 1 Premium Wi-Fi Router",
      "Commitment: 24 months · refundable deposit AED 150 per TV Box (1st bill, adjusted on final bill)",
      "Relocation AED 100 from first relocation onward · 2000 free landline-to-landline minutes (same Emirate)",
      "No landline device included · early termination: 389 + 13 × remaining months (VAT extra)",
    ],
    popular: false,
    accentColor: "#14b8a6",
    planType: "bundle",
    iconKey: "tv",
    image: "/logo.png",
    categoryId: "cat-bundle",
    stockStatus: "in_stock",
    featured: false,
    hidePrice: false,
    whatsappRedirect: false,
    createdAt: now(),
    updatedAt: now(),
  },
  {
    id: "prod-home-basic-ultra",
    name: "DU Home Basic",
    description: "1 Gbps fiber · 24-month commitment",
    price: 322,
    originalPrice: 429,
    pricePeriod: "/month + 5% VAT",
    features: [
      "Discounted lifetime price: AED 322 + 5% VAT = AED 338.10",
      "Speed: 1 Gbps · TV add-on: 2 streaming services",
      "Devices: 1 TV Box + 1 Premium Wi-Fi Router",
      "Commitment: 24 months · refundable deposit AED 150 per TV Box (1st bill, adjusted on final bill)",
      "Relocation AED 100 from first relocation onward · 2000 free landline-to-landline minutes (same Emirate)",
      "No landline device included · early termination: 429 + 17 × remaining months (VAT extra)",
    ],
    popular: true,
    accentColor: "#00C2FF",
    planType: "bundle",
    iconKey: "tv",
    image: "/logo.png",
    categoryId: "cat-bundle",
    stockStatus: "in_stock",
    featured: true,
    hidePrice: false,
    whatsappRedirect: false,
    createdAt: now(),
    updatedAt: now(),
  },
  {
    id: "prod-home-advanced-ultra",
    name: "DU Home Advanced",
    description: "High-speed fiber · 24-month commitment",
    price: 412,
    originalPrice: 549,
    pricePeriod: "/month + 5% VAT",
    features: [
      "Discounted lifetime price: AED 412 + 5% VAT = AED 432.60",
      "High-speed fiber internet · 3 premium TV packages · 3 streaming services included",
      "Devices: 1 Premium Wi-Fi Router",
      "Commitment: 24 months · refundable deposit AED 150 per TV Box (1st bill, adjusted on final bill)",
      "Relocation AED 100 from first relocation onward · 2000 free landline-to-landline minutes (same Emirate)",
      "No landline device included · early termination: 549 + 34 × remaining months (VAT extra)",
    ],
    popular: false,
    accentColor: "#7c3aed",
    planType: "bundle",
    iconKey: "tv",
    image: "/logo.png",
    categoryId: "cat-bundle",
    stockStatus: "in_stock",
    featured: false,
    hidePrice: false,
    whatsappRedirect: false,
    createdAt: now(),
    updatedAt: now(),
  },
  {
    id: "prod-home-ultimate-ultra",
    name: "DU Home Ultimate",
    description: "Highest fiber speed · 24-month commitment",
    price: 562,
    originalPrice: 749,
    pricePeriod: "/month + 5% VAT",
    features: [
      "Discounted lifetime price: AED 562 + 5% VAT = AED 590.10",
      "Highest fiber speed · 5 premium TV packages · 4 streaming services included",
      "Devices: 2 Premium Wi-Fi Routers",
      "Commitment: 24 months · refundable deposit AED 150 per TV Box (1st bill, adjusted on final bill)",
      "Relocation AED 100 from first relocation onward · 2000 free landline-to-landline minutes (same Emirate)",
      "No landline device included · early termination: 749 + 42 × remaining months (VAT extra)",
    ],
    popular: false,
    accentColor: "#00C2FF",
    planType: "bundle",
    iconKey: "tv",
    image: "/logo.png",
    categoryId: "cat-bundle",
    stockStatus: "in_stock",
    featured: false,
    hidePrice: false,
    whatsappRedirect: false,
    createdAt: now(),
    updatedAt: now(),
  },
  {
    id: "prod-home-wireless-5g-a",
    name: "DU Home Wireless Plus",
    description: "AED 229/month · unlimited 5G Wi‑Fi · new customers",
    price: 160.3,
    originalPrice: 229,
    pricePeriod: "/month + 5% VAT (promo)",
    features: [
      "Offer valid only for new customers · 30% discount for 3 months: AED 160.30 + 5% VAT = AED 168.32 · auto-applies from 2nd to 4th bill",
      "After 4th month: AED 229 + 5% VAT = AED 240.45",
      "Unlimited 5G Wi‑Fi data · plug & play router (no technician) · speed depends on area 5G coverage",
      "Geo-locked router: first relocation free, AED 100 from 2nd onward · 12-month contract",
      "Early cancellation: AED 229 + (AED 54.6 × remaining months − 1)",
      "Internet-only — no mobile device · any “free phone” promise invalid / unsupported · no extra discounts",
    ],
    popular: false,
    accentColor: "#14b8a6",
    planType: "internet",
    iconKey: "wifi",
    image: "/logo.png",
    categoryId: "cat-internet",
    stockStatus: "in_stock",
    featured: false,
    hidePrice: false,
    whatsappRedirect: false,
    createdAt: now(),
    updatedAt: now(),
  },
  {
    id: "prod-home-wireless-5g-b",
    name: "DU Home Wireless Entertainment",
    description: "AED 299/month · unlimited 5G home internet · new customers",
    price: 209,
    originalPrice: 299,
    pricePeriod: "/month + 5% VAT (promo)",
    features: [
      "Offer valid only for new customers · 30% discount for 6 months: AED 209 + 5% VAT · auto-applies from 2nd to 7th bill",
      "Unlimited 5G home internet (no fiber) · plug & play router · 12-month contract",
      "Early cancellation: AED 299 + (AED 54.6 × remaining months)",
      "Geo-locked router: first relocation free, AED 100 from 2nd onward",
      "Disney+ included · choose any 3 OTT: Prime Video, OSN+, Shahid, Anghami, Viu",
      "Free delivery · Emirates ID only · no smartphone · no additional discounts",
    ],
    popular: true,
    accentColor: "#00C2FF",
    planType: "internet",
    iconKey: "wifi",
    image: "/logo.png",
    categoryId: "cat-internet",
    stockStatus: "in_stock",
    featured: true,
    hidePrice: false,
    whatsappRedirect: true,
    createdAt: now(),
    updatedAt: now(),
  },
  {
    id: "prod-home-wireless-gaming",
    name: "DU Home Wireless Gaming",
    description: "AED 349/month · gaming router · new customers",
    price: 244.3,
    originalPrice: 349,
    pricePeriod: "/month + 5% VAT (promo)",
    features: [
      "Offer valid only for new customers · 30% discount for 6 months: AED 244.30 + 5% VAT = AED 256.15 · bills 2–7",
      "After 7th month: AED 349 + 5% VAT = AED 366.45",
      "Unlimited 5G data · gaming router with AI optimization · early cancellation: AED 349 + (AED 54.6 × remaining months)",
      "Disney+ included · Prime Video, Shahid, Xbox, Anghami, Viu included",
      "Plug & play (no technician) · geo-locked router: first relocation free, AED 100 from 2nd onward",
      "Huawei H155-380 5G CPE V100R001 Plus (Gaming) — AI traffic prioritization for lower latency",
      "Internet only — no mobile device · free phone claims not valid · no additional discounts",
    ],
    popular: false,
    accentColor: "#7c3aed",
    planType: "internet",
    iconKey: "wifi",
    image: "/logo.png",
    categoryId: "cat-internet",
    stockStatus: "in_stock",
    featured: false,
    hidePrice: false,
    whatsappRedirect: false,
    createdAt: now(),
    updatedAt: now(),
  },
]

export const defaultHeroBanner = (): CMSHeroBanner => ({
  id: "hero-default",
  name: "Default homepage hero",
  eyebrow: "UAE · Residential",
  badgeLabel: "Services At Your Doorstep",
  titleBefore: "Home",
  titleHighlight: "Internet",
  subtitle:
    "25% discount for 24 months or 2 months free — router included. Fiber & 5G plans for UAE homes.",
  feature1: "Doorstep signup & installation",
  feature2: "Authorized du partner",
  feature3: "Dedicated customer care",
  primaryCtaLabel: "View Plans",
  primaryCtaHref: "#plans",
  secondaryCtaLabel: "Get Connected",
  secondaryCtaHref: "#contact",
  speedPrimary: "Up to",
  speedHighlight: "1 Gbps",
  heroSideImage: undefined,
  isActive: true,
})

export const seedHeroBanners: CMSHeroBanner[] = [defaultHeroBanner()]

export const seedFeatured: CMSFeaturedConfig = {
  sectionTitle: "Featured picks",
  sectionSubtitle: "Popular plans customers choose most often — updated live from your catalog.",
  productIds: ["prod-home-basic-ultra", "prod-home-wireless-5g-b", "prod-home-advanced-ultra"],
}

export const seedOrders: CMSOrder[] = [
  {
    id: "ord-1001",
    customerName: "Sara Al-Mansoori",
    email: "sara@example.com",
    productId: "prod-home-basic-ultra",
    quantity: 1,
    totalAed: 322,
    status: "processing",
    createdAt: now(),
  },
  {
    id: "ord-1002",
    customerName: "Omar Hassan",
    email: "omar@example.com",
    productId: "prod-home-advanced-ultra",
    quantity: 1,
    totalAed: 412,
    status: "pending",
    createdAt: now(),
  },
  {
    id: "ord-1003",
    customerName: "Priya Nair",
    email: "priya@example.com",
    productId: "prod-home-wireless-5g-b",
    quantity: 2,
    totalAed: 418,
    status: "completed",
    createdAt: now(),
  },
]

/** E.164 digits without `+` — used for `wa.me` links site-wide. */
export const DEFAULT_WHATSAPP_PHONE_DIGITS = "971563656816"

export const seedSettings: CMSSettings = {
  whatsappPhoneDigits: DEFAULT_WHATSAPP_PHONE_DIGITS,
  totalUsersDisplay: 12840,
  plansSectionTitle: "Home Packages",
  plansSectionSubtitle:
    "Authorized partner offers for residential plans — pricing shown includes promotional terms where noted (+ 5% VAT). Fees & charges may apply (T&C).",
}

export function buildInitialCmsState() {
  return {
    categories: seedCategories,
    products: seedProducts,
    heroBanners: seedHeroBanners,
    featured: seedFeatured,
    orders: seedOrders,
    settings: seedSettings,
    recentUpdates: [] as import("@/lib/cms/types").CMSRecentUpdate[],
  }
}
