import type {
  CMSCategory,
  CMSFeaturedConfig,
  CMSHeroBanner,
  CMSOrder,
  CMSProduct,
  CMSSettings,
} from "@/lib/cms/types"

const now = () => new Date().toISOString()

export const seedCategories: CMSCategory[] = [
  {
    id: "cat-internet",
    name: "Internet Only",
    slug: "internet-only",
    planType: "internet",
    description: "5G & fiber internet packages",
  },
  {
    id: "cat-bundle",
    name: "Internet + TV + Landline",
    slug: "home-bundles",
    planType: "bundle",
    description: "Ultra bundles with TV & voice",
  },
  {
    id: "cat-business",
    name: "Corporate Packages",
    slug: "corporate",
    planType: "business",
    description: "Business connectivity & voice",
  },
]

export const seedProducts: CMSProduct[] = [
  {
    id: "prod-home-starter-ultra",
    name: "Home Starter Ultra",
    description: "250 Mbps download · 24-month offer",
    price: 272,
    originalPrice: 389,
    pricePeriod: "/month + 5% VAT",
    features: [
      "30% discount — 24-months offer",
      "24 months contract (+ fees & charges, T&C apply)",
      "Advanced WiFi router",
      "Free installation & no home deposit",
      "Light English Pack: 1 pack of your choice",
      "1 HDTV receiver",
    ],
    popular: false,
    accentColor: "#14b8a6",
    planType: "bundle",
    iconKey: "tv",
    image: "/logo.png",
    categoryId: "cat-bundle",
    stockStatus: "in_stock",
    featured: false,
    hidePrice: false,
    whatsappRedirect: false,
    createdAt: now(),
    updatedAt: now(),
  },
  {
    id: "prod-home-basic-ultra",
    name: "Home Basic Ultra",
    description: "1 Gbps download · 24-month offer",
    price: 322,
    originalPrice: 429,
    pricePeriod: "/month + 5% VAT",
    features: [
      "25% discount for 24 months",
      "24 months contract (+ 5% VAT + fees & charges, T&C apply)",
      "Advanced WiFi router",
      "Free installation & no home deposit",
      "2 streaming services + 1 TV package",
      "1 recordable HDTV receiver · Disney+ included",
    ],
    popular: true,
    accentColor: "#00C2FF",
    planType: "bundle",
    iconKey: "tv",
    image: "/logo.png",
    categoryId: "cat-bundle",
    stockStatus: "in_stock",
    featured: true,
    hidePrice: false,
    whatsappRedirect: false,
    createdAt: now(),
    updatedAt: now(),
  },
  {
    id: "prod-home-advanced-ultra",
    name: "Home Advanced Ultra",
    description: "1 Gbps download · 24-month offer",
    price: 434,
    originalPrice: 579,
    pricePeriod: "/month + 5% VAT",
    features: [
      "25% discount for 24 months",
      "24 months contract (+ 5% VAT + fees & charges, T&C apply)",
      "2 premium WiFi routers",
      "Free installation & no home deposit",
      "3 streaming services + 2 TV packages",
      "1 recordable HDTV receiver · Disney+ included",
    ],
    popular: false,
    accentColor: "#7c3aed",
    planType: "bundle",
    iconKey: "tv",
    image: "/logo.png",
    categoryId: "cat-bundle",
    stockStatus: "in_stock",
    featured: false,
    hidePrice: false,
    whatsappRedirect: false,
    createdAt: now(),
    updatedAt: now(),
  },
  {
    id: "prod-home-ultimate-ultra",
    name: "Home Ultimate Ultra",
    description: "1 Gbps download · 24-month offer",
    price: 562,
    originalPrice: 749,
    pricePeriod: "/month + 5% VAT",
    features: [
      "25% discount for 24 months",
      "24 months contract (+ 5% VAT + fees & charges, T&C apply)",
      "2 ultimate WiFi routers",
      "Free installation & no home deposit",
      "4 streaming services + 3 TV packages",
      "2 recordable HDTV receivers · Disney+ included",
    ],
    popular: false,
    accentColor: "#00C2FF",
    planType: "bundle",
    iconKey: "tv",
    image: "/logo.png",
    categoryId: "cat-bundle",
    stockStatus: "in_stock",
    featured: false,
    hidePrice: false,
    whatsappRedirect: false,
    createdAt: now(),
    updatedAt: now(),
  },
  {
    id: "prod-home-wireless-5g-a",
    name: "Home Wireless 5G (Plan A)",
    description: "Unlimited data · limited-time offer",
    price: 229,
    originalPrice: 299,
    pricePeriod: "/month + 5% VAT",
    features: [
      "20% discount for 12 months (was AED 299 + VAT)",
      "5G enabled router",
      "Unlimited data",
      "12 months contract",
    ],
    popular: false,
    accentColor: "#14b8a6",
    planType: "internet",
    iconKey: "wifi",
    image: "/logo.png",
    categoryId: "cat-internet",
    stockStatus: "in_stock",
    featured: false,
    hidePrice: false,
    whatsappRedirect: false,
    createdAt: now(),
    updatedAt: now(),
  },
  {
    id: "prod-home-wireless-5g-b",
    name: "Home Wireless 5G (Plan B)",
    description: "Unlimited data · limited-time offer",
    price: 299,
    originalPrice: 399,
    pricePeriod: "/month + 5% VAT",
    features: [
      "20% discount for 6 months (was AED 399 + VAT)",
      "Free router with latest WiFi 6 technology",
      "Unlimited data",
      "12 months contract",
      "Includes Amazon Prime, OSN+, Disney+, Botim (where applicable)",
    ],
    popular: true,
    accentColor: "#00C2FF",
    planType: "internet",
    iconKey: "wifi",
    image: "/logo.png",
    categoryId: "cat-internet",
    stockStatus: "in_stock",
    featured: true,
    hidePrice: false,
    whatsappRedirect: true,
    createdAt: now(),
    updatedAt: now(),
  },
  {
    id: "prod-biz-essential-100",
    name: "Business Essential 100",
    description: "100 Mbps download / 10 Mbps upload",
    price: 810,
    originalPrice: null,
    pricePeriod: "/month + 5% VAT",
    features: [
      "Unlimited internet usage at full speed",
      "Affordable rates",
      "Dedicated account manager",
      "Flexible no-contract option at AED 1,850/month",
      "One-time activation AED 200 + 5% VAT",
      "T&C apply",
    ],
    popular: false,
    accentColor: "#00C2FF",
    planType: "business",
    iconKey: "building",
    image: "/logo.png",
    categoryId: "cat-business",
    stockStatus: "in_stock",
    featured: false,
    hidePrice: false,
    whatsappRedirect: false,
    createdAt: now(),
    updatedAt: now(),
  },
  {
    id: "prod-biz-essential-150",
    name: "Business Essential 150",
    description: "150 Mbps download / 15 Mbps upload",
    price: 950,
    originalPrice: null,
    pricePeriod: "/month + 5% VAT",
    features: [
      "Unlimited internet usage at full speed",
      "Affordable rates",
      "Dedicated account manager",
      "Flexible no-contract option at AED 2,250/month",
      "One-time activation AED 200 + 5% VAT",
      "T&C apply",
    ],
    popular: false,
    accentColor: "#7c3aed",
    planType: "business",
    iconKey: "building",
    image: "/logo.png",
    categoryId: "cat-business",
    stockStatus: "low_stock",
    featured: false,
    hidePrice: false,
    whatsappRedirect: false,
    createdAt: now(),
    updatedAt: now(),
  },
  {
    id: "prod-biz-ultimate-200",
    name: "Business Ultimate 200",
    description: "200 Mbps download / 40 Mbps upload",
    price: 949,
    originalPrice: null,
    pricePeriod: "/month + 5% VAT",
    features: [
      "Connectivity (Internet + Voice): basic internet router",
      "1 business line + 1 cordless phone, 100 national mobile mins, 100 international mins",
      "Security: 3 antivirus licenses + built-in firewall",
      "Digital presence: 1 .ae domain + e-commerce starter kit (1 year free)",
      "Productivity: 2× Microsoft 365 Business Basic licenses",
      "Access point or handset voucher (1 add-on included)",
      "Monthly plan after 24 months: AED 1,249 (T&C apply)",
    ],
    popular: false,
    accentColor: "#14b8a6",
    planType: "business",
    iconKey: "building",
    image: "/logo.png",
    categoryId: "cat-business",
    stockStatus: "in_stock",
    featured: false,
    hidePrice: false,
    whatsappRedirect: false,
    createdAt: now(),
    updatedAt: now(),
  },
  {
    id: "prod-biz-ultimate-400",
    name: "Business Ultimate 400",
    description: "400 Mbps download / 80 Mbps upload",
    price: 1299,
    originalPrice: null,
    pricePeriod: "/month + 5% VAT",
    features: [
      "Connectivity (Internet + Voice): basic internet router",
      "1 business line + 1 cordless phone, 100 national mobile mins, 100 international mins",
      "Security: 3 antivirus licenses + built-in firewall",
      "Digital presence: 1 .ae domain + e-commerce starter kit (1 year free)",
      "Productivity: 2× Microsoft 365 Business Basic licenses",
      "Access point or handset voucher (1 add-on included)",
      "Monthly plan after 24 months: AED 1,599 (T&C apply)",
    ],
    popular: true,
    accentColor: "#7c3aed",
    planType: "business",
    iconKey: "building",
    image: "/logo.png",
    categoryId: "cat-business",
    stockStatus: "in_stock",
    featured: true,
    hidePrice: false,
    whatsappRedirect: false,
    createdAt: now(),
    updatedAt: now(),
  },
  {
    id: "prod-biz-ultimate-600",
    name: "Business Ultimate 600",
    description: "600 Mbps download / 120 Mbps upload",
    price: 1699,
    originalPrice: null,
    pricePeriod: "/month + 5% VAT",
    features: [
      "Connectivity (Internet + Voice): basic internet router",
      "1 business line + 1 cordless phone, 100 national mobile mins, 100 international mins",
      "Security: 3 antivirus licenses + built-in firewall",
      "Digital presence: 1 .ae domain + e-commerce starter kit (1 year free)",
      "Productivity: 2× Microsoft 365 Business Basic licenses",
      "Access point or handset voucher (1 add-on included)",
      "Monthly plan after 24 months: AED 1,999 (T&C apply)",
    ],
    popular: false,
    accentColor: "#00C2FF",
    planType: "business",
    iconKey: "building",
    image: "/logo.png",
    categoryId: "cat-business",
    stockStatus: "in_stock",
    featured: false,
    hidePrice: false,
    whatsappRedirect: false,
    createdAt: now(),
    updatedAt: now(),
  },
  {
    id: "prod-biz-ultimate-800",
    name: "Business Ultimate 800",
    description: "800 Mbps download / 160 Mbps upload",
    price: 2299,
    originalPrice: null,
    pricePeriod: "/month + 5% VAT",
    features: [
      "Connectivity (Internet + Voice): advanced internet router",
      "1 business line + 2 cordless phones, 100 national mobile mins, 100 international mins",
      "Security: 10 antivirus licenses + built-in firewall",
      "Digital presence: 1 .ae domain + e-commerce starter kit (1 year free)",
      "Productivity: 5× Microsoft 365 Business Basic licenses",
      "1 trunk line included (2 add-ons included)",
      "Monthly plan after 24 months: AED 2,599 (T&C apply)",
    ],
    popular: false,
    accentColor: "#14b8a6",
    planType: "business",
    iconKey: "building",
    image: "/logo.png",
    categoryId: "cat-business",
    stockStatus: "in_stock",
    featured: false,
    hidePrice: false,
    whatsappRedirect: false,
    createdAt: now(),
    updatedAt: now(),
  },
  {
    id: "prod-biz-ultimate-1gbps",
    name: "Business Ultimate 1 Gbps",
    description: "1 Gbps download / 200 Mbps upload",
    price: 3149,
    originalPrice: null,
    pricePeriod: "/month + 5% VAT",
    features: [
      "Connectivity (Internet + Voice): Pro internet router",
      "1 business line + 3 cordless phones, 100 national mobile mins, 100 international mins",
      "Security: 20 antivirus licenses + built-in firewall",
      "Digital presence: 1 .ae domain + e-commerce starter kit (1 year free)",
      "Productivity: 8× Microsoft 365 Business Basic licenses",
      "1 free trunk line + 2 extensions (3 add-ons included)",
      "Monthly plan after 24 months: AED 3,499 (T&C apply)",
    ],
    popular: false,
    accentColor: "#7c3aed",
    planType: "business",
    iconKey: "building",
    image: "/logo.png",
    categoryId: "cat-business",
    stockStatus: "in_stock",
    featured: false,
    hidePrice: false,
    whatsappRedirect: false,
    createdAt: now(),
    updatedAt: now(),
  },
  {
    id: "prod-biz-complete",
    name: "Business Complete Plan",
    description: "100 Mbps download · 12-month contract",
    price: 475,
    originalPrice: 950,
    pricePeriod: "/month + 5% VAT",
    features: [
      "50% off — promotional rate for first 6 months",
      "1 business line + unlimited landline calls",
      "100 mobile minutes + 100 international minutes",
      "Standard internet router + built-in firewall",
      "1× Microsoft 365 license + 1 .ae domain & hosting",
      "Available in Abu Dhabi, Sharjah, Ajman, UAQ, RAK & Fujairah",
    ],
    popular: false,
    accentColor: "#00C2FF",
    planType: "business",
    iconKey: "building",
    image: "/logo.png",
    categoryId: "cat-business",
    stockStatus: "in_stock",
    featured: false,
    hidePrice: false,
    whatsappRedirect: false,
    createdAt: now(),
    updatedAt: now(),
  },
  {
    id: "prod-biz-starter-pro-ll",
    name: "Business Starter Pro (Landline + 5G)",
    description: "Fixed broadband with 5G-enabled router",
    price: 279,
    originalPrice: 399,
    pricePeriod: "/month + 5% VAT",
    features: [
      "30% off — save 30% for 6 months",
      "One-time activation AED 200 + VAT",
      "Business landline included",
      "Unlimited internet usage at full speed",
      "Unlimited landline calls + 250 national mobile minutes",
      "1× Microsoft 365 Business Basic license + 1 .ae domain",
      "Landline device included",
    ],
    popular: false,
    accentColor: "#00C2FF",
    planType: "business",
    iconKey: "building",
    image: "/logo.png",
    categoryId: "cat-business",
    stockStatus: "in_stock",
    featured: false,
    hidePrice: false,
    whatsappRedirect: false,
    createdAt: now(),
    updatedAt: now(),
  },
  {
    id: "prod-biz-starter-pro-bb",
    name: "Business Starter Pro (Broadband)",
    description: "Fixed broadband with 5G-enabled router",
    price: 249,
    originalPrice: 299,
    pricePeriod: "/month + 5% VAT",
    features: [
      "30% off — save 30% for 6 months",
      "One-time activation AED 200 + VAT",
      "Unlimited internet usage at full speed",
      "Advanced WiFi with Gigabit Ethernet port",
      "Free e-commerce starter kit (1st year): domain + website + EStore + 5 emails",
      "Internet calling pack (free for 3 months)",
    ],
    popular: false,
    accentColor: "#7c3aed",
    planType: "business",
    iconKey: "building",
    image: "/logo.png",
    categoryId: "cat-business",
    stockStatus: "in_stock",
    featured: false,
    hidePrice: false,
    whatsappRedirect: false,
    createdAt: now(),
    updatedAt: now(),
  },
  {
    id: "prod-biz-starter-ultra",
    name: "Business Starter Ultra",
    description: "5G unlimited broadband · 12-month contract",
    price: 499,
    originalPrice: 799,
    pricePeriod: "/month + 5% VAT",
    features: [
      "37.5% off — save for 24 months",
      "One-time activation AED 200 + VAT",
      "Free 5G-enabled router + 5G unlimited internet at full speed",
      "2 business landlines + 250 national minutes per landline",
      "Unlimited national landline-to-landline calls",
      "2× Microsoft 365 Business Basic licenses + 1 free .ae domain",
      "5 antivirus licenses + 2 landline devices",
    ],
    popular: false,
    accentColor: "#14b8a6",
    planType: "business",
    iconKey: "building",
    image: "/logo.png",
    categoryId: "cat-business",
    stockStatus: "out_of_stock",
    featured: false,
    hidePrice: false,
    whatsappRedirect: false,
    createdAt: now(),
    updatedAt: now(),
  },
]

export const defaultHeroBanner = (): CMSHeroBanner => ({
  id: "hero-default",
  name: "Default homepage hero",
  eyebrow: "UAE · Residential & Business",
  badgeLabel: "Services At Your Doorstep",
  titleBefore: "Home",
  titleHighlight: "Internet",
  subtitle:
    "25% discount for 24 months or 2 months free — router included. Fiber & 5G plans for UAE homes and businesses.",
  feature1: "Doorstep signup & installation",
  feature2: "Authorized du partner",
  feature3: "Dedicated customer care",
  primaryCtaLabel: "View Plans",
  primaryCtaHref: "#plans",
  secondaryCtaLabel: "Get Connected",
  secondaryCtaHref: "#contact",
  speedPrimary: "Up to",
  speedHighlight: "1 Gbps",
  heroSideImage: undefined,
  isActive: true,
})

export const seedHeroBanners: CMSHeroBanner[] = [defaultHeroBanner()]

export const seedFeatured: CMSFeaturedConfig = {
  sectionTitle: "Featured picks",
  sectionSubtitle: "Popular plans customers choose most often — updated live from your catalog.",
  productIds: ["prod-home-basic-ultra", "prod-home-wireless-5g-b", "prod-biz-ultimate-400"],
}

export const seedOrders: CMSOrder[] = [
  {
    id: "ord-1001",
    customerName: "Sara Al-Mansoori",
    email: "sara@example.com",
    productId: "prod-home-basic-ultra",
    quantity: 1,
    totalAed: 322,
    status: "processing",
    createdAt: now(),
  },
  {
    id: "ord-1002",
    customerName: "Omar Hassan",
    email: "omar@example.com",
    productId: "prod-biz-ultimate-400",
    quantity: 1,
    totalAed: 1299,
    status: "pending",
    createdAt: now(),
  },
  {
    id: "ord-1003",
    customerName: "Priya Nair",
    email: "priya@example.com",
    productId: "prod-home-wireless-5g-b",
    quantity: 2,
    totalAed: 598,
    status: "completed",
    createdAt: now(),
  },
]

export const seedSettings: CMSSettings = {
  whatsappPhoneDigits: "97144310766",
  totalUsersDisplay: 12840,
  plansSectionTitle: "Home & Corporate Packages",
  plansSectionSubtitle:
    "Authorized partner offers for home and business — pricing shown includes promotional terms where noted (+ 5% VAT). Fees & charges may apply (T&C).",
}

export function buildInitialCmsState() {
  return {
    categories: seedCategories,
    products: seedProducts,
    heroBanners: seedHeroBanners,
    featured: seedFeatured,
    orders: seedOrders,
    settings: seedSettings,
    recentUpdates: [] as import("@/lib/cms/types").CMSRecentUpdate[],
  }
}
